/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./public/**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#efe8ce",
        "on-secondary-fixed-variant": "#5c5b5b",
        "primary": "#755700",
        "primary-dim": "#664b00",
        "error-dim": "#b92902",
        "tertiary-container": "#fc9e00",
        "tertiary": "#835000",
        "on-secondary-fixed": "#403f3f",
        "surface": "#fdf6df",
        "secondary": "#5c5b5b",
        "on-tertiary-fixed": "#2a1600",
        "tertiary-dim": "#734500",
        "on-surface-variant": "#5f5c4a",
        "on-tertiary": "#fff0e4",
        "error-container": "#f95630",
        "primary-container": "#fdc003",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#525151",
        "surface-tint": "#755700",
        "surface-container-lowest": "#ffffff",
        "on-background": "#322f20",
        "surface-container-high": "#eae3c7",
        "inverse-on-surface": "#a29d89",
        "outline-variant": "#b3ad98",
        "surface-dim": "#dcd5b6",
        "on-primary": "#fff1db",
        "secondary-container": "#e5e2e1",
        "surface-variant": "#e4ddc0",
        "on-primary-container": "#553e00",
        "inverse-surface": "#100e04",
        "on-error": "#ffefec",
        "on-error-container": "#520c00",
        "secondary-dim": "#504f4f",
        "outline": "#7b7764",
        "secondary-fixed-dim": "#d6d4d3",
        "on-tertiary-fixed-variant": "#573300",
        "on-primary-fixed-variant": "#604700",
        "surface-bright": "#fdf6df",
        "surface-container-low": "#f8f1d8",
        "tertiary-fixed": "#fc9e00",
        "primary-fixed-dim": "#ecb200",
        "tertiary-fixed-dim": "#e99200",
        "on-primary-fixed": "#3d2b00",
        "background": "#fdf6df",
        "on-secondary": "#f5f2f1",
        "primary-fixed": "#fdc003",
        "on-tertiary-container": "#4b2c00",
        "error": "#b02500",
        "surface-container-highest": "#e4ddc0",
        "inverse-primary": "#fdc003",
        "on-surface": "#322f20"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Be Vietnam Pro"],
        "label": ["Be Vietnam Pro"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
